### ISSUE TITLE
运行过程中报错，无法登录

### ISSUE THREAD

**Issue by zhengjinzhj** [xianhu/LearnPython#12]
请问你用的什么环境？我用的是Python2.7，在运行过程中报错：
2016-11-09 21:57:24,653	INFO	Starting new HTTP connection (1): 127.0.0.1
2016-11-09 21:57:27,233	DEBUG	"GET http://weibo.com/login.php HTTP/1.1" 200 None
2016-11-09 21:57:31,757	INFO	Resetting dropped connection: 127.0.0.1
2016-11-09 21:57:31,871	DEBUG	"GET http://login.sina.com.cn/sso/prelogin.php?checkpin=1&su=&callback=sinaSSOController.preloginCallBack&rsakt=mod&client=ssologin.js%28v1.4.18%29&entry=weibo&_=1478699847240 HTTP/1.1" 200 None
2016-11-09 21:57:31,872	DEBUG	WeiBoLogin get_json_data: {u'nonce': u'RHMSEX', u'rsakv': u'1330428213', u'retcode': 0, u'exectime': 9, u'servertime': 1478699850, u'pcid': u'gz-789fcba1ca6723b1b64d880551d5c5b0081e', u'pubkey': u'EB2A38568661887FA180BDDB5CABD5F21C7BFD59C090CB2D245A87AC253062882729293E5506350508E7F9AA3BB77F4333231490F915F6D63C55FE2F08A49B353F444AD3993CACC02DB784ABBB8E42A9B1BBFFFB38BE18D78E87A0E41B9B8F73A928EE0CCEE1F6739884B9777E4FE9E88A1BBE495927AC4A799B3181D6442443'}
2016-11-09 21:57:36,384	INFO	Resetting dropped connection: 127.0.0.1
2016-11-09 21:57:36,696	DEBUG	"POST http://login.sina.com.cn/sso/login.php?client=ssologin.js(v1.4.18)&_=1478699851 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "C:/Users/zheng/PycharmProjects/spider/weibo.py", line 159, in <module>
    weibo.login()
  File "C:/Users/zheng/PycharmProjects/spider/weibo.py", line 92, in login
    json_data_1 = self.session.post(login_url_1, data=post_data).json()
  File "C:\Python27\lib\requests\models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: **No JSON object could be decoded**

**Comment by xianhu** [comment]
建议改用3.5+试试。另外，报错信息很明确，建议自行修改。
